import Header from "@/components/Header";
import Footer from "@/components/Footer";
import {Wrapper} from "@/styled components/Home-style";
import MobileHeader from "@/components/mobile_header";
import MobileMenu from "@/components/mobile_Menu";
import Head from "next/head";

function Layout({children}) {
    return (
        <>
            <Head>
                <title>talay to</title>
                <link rel="icon" href='/ring2.png' />
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <Wrapper>
            <Header/>
            <MobileHeader/>
            {children}
            <Footer/>
        </Wrapper>
        </>
    );
}

export default Layout;